---
title: "Codebook EFH 2014"
author: "Cristóbal Montt"
date: "25 de abril de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo = FALSE, warnings = FALSE, message=FALSE, results = "hide"}

# load data ====================================================================

setwd("C:/Users/lorel_000/Google Drive/efh2014")

# Instalar paquetes necesarios si no estan instalados
list_packages <- c("haven", "dplyr", "DT")
new_packages <- list_packages[!(list_packages %in% 
                                        installed.packages()[, "Package"])] 
if(length(new_packages)) {install.packages(new_packages)}

# Cargar paquetes necesarios
sapply(list_packages, require, character.only = TRUE, quietly = TRUE)
```

```{r echo = FALSE, warnings = FALSE, message=FALSE}

# Cargar base de datos
efh <- read_dta(file = "EFH_2014_allvars_pub.dta")
#efh[efh==NaN] <- NA
efh[efh=="NaN"] <- NA

library(DT)
# diccionario etiqueta variables
# agregar tipo varaible?

variables <- names(efh)
etiqueta_variables <- unname(sapply(efh, function(x) attributes(x)$label))
diccionario <- as.data.frame(cbind(variables, etiqueta_variables))
datatable(diccionario)
# ver https://rstudio.github.io/DT/
```

